builds:
  43cb587e6cf7665ff51f7aad84a4486c27ae7e15890d7cc1163c36a85b8b967e:
    version: 43cb587e6cf7665ff51f7aad84a4486c27ae7e15890d7cc1163c36a85b8b967e
    blobstore_id: eb6a8280-fe07-4ff4-5d0b-c709a17a3733
    sha1: sha256:ee13b82aad145bdcd7cad2936e7cdf9de9fa66f0883d095efe934a072268962b
  85d418a7debb01fc4825c28cef3da558757af57c:
    version: 85d418a7debb01fc4825c28cef3da558757af57c
    blobstore_id: d845ae86-ca61-4507-6a0b-d1dc5b1f6a44
    sha1: 9e73cc4bdbbb26e36e192fe8fd28088ee7f78a56
  8c5223f4e7e5adcb05299cdbd4c5d9028fc5ea6b:
    version: 8c5223f4e7e5adcb05299cdbd4c5d9028fc5ea6b
    blobstore_id: 332fb4fa-334f-4e4e-682a-42be06c5fc55
    sha1: b71a7ad6fc633dc8dd3dcb8679614039b3d940b0
  a2497e9c5ddd4920162643793d625bcf9a9873c7:
    version: a2497e9c5ddd4920162643793d625bcf9a9873c7
    blobstore_id: d095d360-4e13-4988-5ab0-157a33f270df
    sha1: 404349ca76d44ccbf8c6faddeca317820f39333a
  cc9d2c04acabe975800122fa0a5b1cd4c2a65bae:
    version: cc9d2c04acabe975800122fa0a5b1cd4c2a65bae
    blobstore_id: 42f5f4e2-171c-4d1d-57c4-451dfed58081
    sha1: d790845c40a550cd0e37f6faa606b730e71f6309
  d14d15e706d5e547414843be6603b58eeba05249:
    version: d14d15e706d5e547414843be6603b58eeba05249
    blobstore_id: 55632f00-a1cd-4e10-5165-768ea0d97849
    sha1: 7005f7de6d944b7f09a02d56ee7e23e642a03cad
format-version: "2"
