cni/cni-amd64-v0.5.2.tgz:
  size: 14085755
  object_id: 31cb39af-c33d-4df8-4d45-c02541806e39
  sha: 71f411080245aa14d0cc06f6824e8039607dd9e9
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
container-images/gcr.io_google_containers_k8s-dns-dnsmasq-nanny-amd64:1.14.8.tgz:
  size: 10940805
  object_id: 97a35aca-59c0-4e22-7d05-cc0de22f1e08
  sha: fdec9e001af4290f638e30ae381cda27b6e964f5
container-images/gcr.io_google_containers_k8s-dns-kube-dns-amd64:1.14.8.tgz:
  size: 13181223
  object_id: 730ad60c-29ed-4bf4-52e2-3f82bf5d281e
  sha: 4f3058395927070aac9bf6085bd638cbf4236cbb
container-images/gcr.io_google_containers_k8s-dns-sidecar-amd64:1.14.8.tgz:
  size: 11240942
  object_id: 7b67f40e-6428-4441-459b-858ef4151389
  sha: 71f699220f8685114493ac82428835294eaea869
container-images/gcr.io_google_containers_kubernetes-dashboard-amd64:v1.8.2.tgz:
  size: 37217815
  object_id: c3b9d396-8537-498d-403a-3afc628ee3c7
  sha: de1fc537fa30c9547087a64ceb36e415b38f37ae
container-images/gcr.io_google_containers_pause-amd64:3.0.tgz:
  size: 313309
  object_id: 7af46f58-b711-491a-4142-048930964b81
  sha: 51d94c9d97106024454f20bf443132058e3d9334
container-images/gcr.io_google_containers_pause.tgz:
  size: 71680
  object_id: 018df5e0-9afe-4f68-4552-c08a692a991e
  sha: 7b82730258d143602b85efa7ec2da5bc754f3a93
container-images/k8s.gcr.io_heapster-amd64:v1.5.0.tgz:
  size: 19853400
  object_id: 3fd4b0ad-3e1b-4ba7-7d71-d600dc8283ea
  sha: 0698cdc1e91d7d57e0bccf86a7a7e13dc02fe3c0
container-images/k8s.gcr.io_heapster-influxdb-amd64:v1.3.3.tgz:
  size: 4751608
  object_id: 72e0b4f1-269e-4174-4e47-e1598bf0e8cb
  sha: d116fc1985e78f7fa116a10a538ada383d867da8
etcdctl-3.0.7:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flannel-v0.9.1-linux-amd64.tar.gz:
  size: 9084492
  object_id: 0672c984-dd38-4db1-5efd-0515a0ace8ee
  sha: 9d92bf991341163a16a6b9c1a54d45466826a658
go/go1.9.2.linux-amd64.tar.gz:
  size: 104247844
  object_id: 9dd1786f-8cda-4ce4-4a95-6fe98ed237d5
  sha: 94c889e039e3d2e94ed95e8f8cb747c5bc1c2b58
govc_v0.16.0_linux_amd64.gz:
  size: 7941649
  object_id: a1f90508-10d4-4f13-43b6-4974e47b29c3
  sha: fed663701376d9f0896eb2fe9f9fc5aaeee1c3dd
jq-linux64-1.5:
  size: 3027945
  object_id: 41eb1cd1-0377-4e08-5602-51e0af8b9b52
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
kubernetes-1.9.3/kube-apiserver:
  size: 209306907
  object_id: fafef981-581c-4b23-7239-191535c508fb
  sha: 78d2494d7143aa4548ea5faedbdefcbdd57930e4
kubernetes-1.9.3/kube-controller-manager:
  size: 136680621
  object_id: dda910dc-6c3c-4d7f-556a-42b2c980b439
  sha: dc5d59d39ca65eb8254c87df4e461ff4c6a0a564
kubernetes-1.9.3/kube-proxy:
  size: 63378854
  object_id: 57e00638-c0dd-46fd-6a4b-d008f6c6f21b
  sha: 2b127358a4780d54a431fafbd134874a48c30e74
kubernetes-1.9.3/kube-scheduler:
  size: 61566871
  object_id: 3490dcb0-8c8f-4c3f-4a25-3e323ce9f915
  sha: 34b09e6675503d178ea92c8a691e1a22838b7e48
kubernetes-1.9.3/kubectl:
  size: 67390456
  object_id: 20ce4d03-62a5-466a-601a-75f7da8b45da
  sha: a27d808eb011dbeea876fe5326349ed167a7ed28
kubernetes-1.9.3/kubelet:
  size: 147799384
  object_id: 3a4dabed-b06d-4900-58f5-ceb7a9c6f666
  sha: ef979a00ba2f7bf4ee5023e82f94ced2d94c1726
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
