cni/cni-amd64-v0.5.2.tgz:
  size: 14085755
  object_id: 31cb39af-c33d-4df8-4d45-c02541806e39
  sha: 71f411080245aa14d0cc06f6824e8039607dd9e9
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
conntrack/conntrack_1.4.1-1.deb:
  size: 25112
  object_id: 9bf859c2-93aa-48b0-69f9-5903f0b4acbe
  sha: 494df11d77a1dd31fbc1e0e8c7946957ef5a74af
conntrack/libmnl0_1.0.3-3.deb:
  size: 11416
  object_id: 245e085f-1ad2-447d-67bb-1894b960c571
  sha: dcb0b572f1207ad192d8cb1a9010fc6dd22d0000
conntrack/libnetfilter-conntrack3_1.0.4-1.deb:
  size: 45872
  object_id: 42a59368-8ae3-4502-480b-56ecd3f40f7a
  sha: 743b497bd6a6491a8cad11c04103e55c7a9cc93c
container-images/gcr.io_google_containers_k8s-dns-dnsmasq-nanny-amd64:1.14.10.tgz:
  size: 10980446
  object_id: 80191878-fd78-4d9a-6ad3-bff1224300a9
  sha: ba8ca62dc4fcf71a40c894d6f63e017c9d853ed8
container-images/gcr.io_google_containers_k8s-dns-kube-dns-amd64:1.14.10.tgz:
  size: 13175598
  object_id: 7703b9a6-bd1f-46a2-7811-1814b1806987
  sha: aa2447a1e80fa1e8177dc606018c74e2606b9925
container-images/gcr.io_google_containers_k8s-dns-sidecar-amd64:1.14.10.tgz:
  size: 11294012
  object_id: cccdc7cf-33dd-4939-6000-84e4c16baf97
  sha: fd2d82294bcbefb87349446d388bfe12ebd0ca0f
container-images/gcr.io_google_containers_kubernetes-dashboard-amd64:v1.8.3.tgz:
  size: 37223449
  object_id: 939c66c1-9114-4573-6d73-8f6cfa82d879
  sha: 07b3295679780fbcff32781da038151ab7a8c14b
container-images/gcr.io_google_containers_pause-amd64:3.0.tgz:
  size: 313309
  object_id: 7af46f58-b711-491a-4142-048930964b81
  sha: 51d94c9d97106024454f20bf443132058e3d9334
container-images/gcr.io_google_containers_pause-amd64:3.1.tgz:
  size: 315603
  object_id: f92d6acb-bbc9-4ca5-6ca1-653738fd862c
  sha: 9b69b5e7b9483ccf531d382bcfe3eb77023b0358
container-images/k8s.gcr.io_heapster-amd64:v1.5.2.tgz:
  size: 19851726
  object_id: 50fadeb4-1f8f-42fb-749c-b8565388bce9
  sha: 0ec31bdc47491b7bc93f81724c2829829d725720
container-images/k8s.gcr.io_heapster-influxdb-amd64:v1.3.3.tgz:
  size: 4751608
  object_id: 93e1221a-e955-4d68-562b-0d47dbbb06ea
  sha: 1b2e197e0cccd7c0b7fb2f7ee791b9bc52d0654b
etcdctl-3.0.7:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flannel-v0.10.0-linux-amd64.tar.gz:
  size: 9706487
  object_id: 36a8e66a-0b6c-4ca2-5f27-c277a7db90c5
  sha: 9d19a56847d6aad207671a349eddd85de87ba560
govc_v0.17.1_linux_amd64.gz:
  size: 8062539
  object_id: 454383c5-b65d-4e4e-524e-84ba489a1d3f
  sha: 3f2d0f18df724000731013349e2a703f70c69875
ipset/ipset_6.20.1-1_amd64.deb:
  size: 34156
  object_id: 5dfcce8f-366e-49f0-59e6-9e2d48178750
  sha: 79eb9008d1a57b31bc748b49c18701ab3dd41108
ipset/libipset3_6.20.1-1_amd64.deb:
  size: 50812
  object_id: 67efec49-e111-45fc-701d-7d55dbe66660
  sha: e4daa1ac22b2775d1c334aa6fe055ca8dcccc185
jq-linux64-1.5:
  size: 3027945
  object_id: 41eb1cd1-0377-4e08-5602-51e0af8b9b52
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
kubernetes-1.10.2/kube-apiserver:
  size: 223899881
  object_id: b629ea02-937f-4975-754f-910312daaf4c
  sha: d1fb660e2d45363d4f98b545c1daca785bf46326
kubernetes-1.10.2/kube-controller-manager:
  size: 146716871
  object_id: 1581bd1a-3cee-4ec1-6c42-2f68ef5c282d
  sha: 857b4614a115280abaa115a4654ed1e609730107
kubernetes-1.10.2/kube-proxy:
  size: 51343525
  object_id: 9f322658-57ca-4e46-64cb-d8ec39dcde8d
  sha: e8040448e966ee128d6f48176780204dd27df0cd
kubernetes-1.10.2/kube-scheduler:
  size: 49258944
  object_id: 294d43ef-3974-4eac-644e-e44631e23293
  sha: 7b35c177437d50280fac0477cd6fd1a113d32a3a
kubernetes-1.10.2/kubectl:
  size: 54285796
  object_id: 5c588a70-33cd-490d-5482-c383f0d77834
  sha: 6f1b0de3b9eb191b003734d47e7b07e034b3b645
kubernetes-1.10.2/kubelet:
  size: 152806712
  object_id: fbfb5929-8bda-4104-6d17-b8a472953e7e
  sha: 890bfe2eb15beb4ef0d42ef33db04271542a6c16
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
