cni/cni-amd64-v0.5.2.tgz:
  size: 14085755
  object_id: 727a352b-78a0-4e46-5551-fe7737f99392
  sha: 71f411080245aa14d0cc06f6824e8039607dd9e9
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: d838b9fd-3c7a-458f-551d-5e0ed832a20a
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
container-images/gcr.io_google_containers_exechealthz-amd64:1.1.tgz:
  size: 2870256
  object_id: 5f81ba15-f408-4e6e-53f9-21bc98335601
  sha: 94d3238f950dc5309e817a29ce9f4e459966ce95
container-images/gcr.io_google_containers_heapster:v1.1.0.tgz:
  size: 32207205
  object_id: d992ea4a-698e-44b8-4098-ce3fbefacc20
  sha: 70c7b90bf79d9714a974aa0b422941b568264424
container-images/gcr.io_google_containers_kube-dnsmasq-amd64:1.3.tgz:
  size: 2476131
  object_id: f2aa8c89-ad52-4c75-4978-61ab28169bd7
  sha: 7d83271245ca292683b32841b7cfb27a3a259193
container-images/gcr.io_google_containers_kubedns-amd64:1.7.tgz:
  size: 11894000
  object_id: e37d8b8a-2eae-4170-6216-596da69f26c6
  sha: 9ce0ba73de89e615c7612814a0f06101f55625d5
container-images/gcr.io_google_containers_kubernetes-dashboard-amd64:v1.6.0.tgz:
  size: 29053901
  sha: a49f94b91863986583005118b88e60072e015e75
container-images/gcr.io_google_containers_pause-amd64:3.0.tgz:
  size: 313309
  object_id: a55832b3-1358-4f78-5cf3-df2a3c13994b
  sha: 51d94c9d97106024454f20bf443132058e3d9334
container-images/gcr.io_google_containers_pause.tgz:
  size: 71680
  object_id: c5367513-a4e5-4d40-4216-1a20e61ed223
  sha: 7b82730258d143602b85efa7ec2da5bc754f3a93
container-images/kubernetes_heapster_influxdb:v0.6.tgz:
  size: 105081408
  object_id: d8116f67-f912-4ab6-4017-875dad9b1296
  sha: cc33af2580eead375bb1ebf5d2cacf6dc71477a8
etcdctl:
  size: 18427584
  object_id: 795f11e1-f601-40f1-5405-7729c179ef87
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flanneld:
  size: 21599816
  object_id: 0ae69b4e-5308-4991-611e-41136119bbd7
  sha: 63076521f1ba5605fa5f97016072a4538d66740f
glusterfs-client/attr_1%3a2.4.47-1ubuntu1_amd64.deb:
  size: 29346
  object_id: d53f731d-9859-489a-647d-ed2597fc5dcf
  sha: effe5bf80d830d64ce27675b67b4e21c264197e8
glusterfs-client/fuse_2.9.2-4ubuntu4.14.04.1_amd64.deb:
  size: 25106
  object_id: c018e428-c58d-4cc5-789b-e1d1017a8de2
  sha: d7dde526bc751b118fe296fd8e3d6a7e71251c3c
glusterfs-client/glusterfs-client_3.8.8-ubuntu1~trusty1_amd64.deb:
  size: 19482
  object_id: 7ebb66ef-a8ff-4561-6ab0-c95c2727d7b1
  sha: fdaa5cce3c312e79de29007035a83f2beb165fac
glusterfs-client/glusterfs-common_3.8.8-ubuntu1~trusty1_amd64.deb:
  size: 2890072
  object_id: 7faa4c46-374d-4041-44b9-a4dfb71799cd
  sha: 98f73f56f40722b9090c630551d281a8bec9a70e
glusterfs-client/libaio1_0.3.109-4_amd64.deb:
  size: 6364
  object_id: 8cfd367d-009f-4e77-5c65-4c6b81c28769
  sha: 6ba128949ea62436fd917115d325cf3f2fa83e10
glusterfs-client/libdevmapper-event1.02.1_2%3a1.02.77-6ubuntu2_amd64.deb:
  size: 10812
  object_id: 68efa438-72a0-43bb-6726-27b03f500f13
  sha: 2873ddde9dfa3897918fb48a470fdf6ba511e182
glusterfs-client/libibverbs1_1.1.7-1ubuntu1.1_amd64.deb:
  size: 23608
  object_id: 473e828c-41b7-4a41-5f59-36a246891272
  sha: 80c29a02fa10b669c21a67af480e12067691bb95
glusterfs-client/liblvm2app2.2_2.02.98-6ubuntu2_amd64.deb:
  size: 243236
  object_id: 7d2e5858-2c4b-4949-434f-aad89152c145
  sha: 0c81bd2c10a3f2e9f59550a616cef8366ba33812
glusterfs-client/libpython2.7-minimal_2.7.6-8ubuntu0.3_amd64.deb:
  size: 306648
  object_id: c4fe63c4-d520-4a38-728b-e3bc8b969862
  sha: 268fb6f9fffdab4ad34d018e0f39ade3ca83e61e
glusterfs-client/libpython2.7-stdlib_2.7.6-8ubuntu0.3_amd64.deb:
  size: 1873274
  object_id: 39e0ec8e-8095-4fce-6969-0c14f5b1b10d
  sha: 194436a60fb7e3256e5617cc84f5f03cc0c0f0ae
glusterfs-client/libpython2.7_2.7.6-8ubuntu0.3_amd64.deb:
  size: 1039462
  object_id: 2810efc6-4235-4b0c-5172-204d45f83060
  sha: b74ef212062c7ce6a5f80576b59d914d6a5792cb
glusterfs-client/librdmacm1_1.0.16-1_amd64.deb:
  size: 36818
  object_id: e4a53953-0a37-48c1-798a-9f5c0d5dd1ca
  sha: dd192678b7dbe686b7327ea7c0da2456c3a14d1e
glusterfs-client/liburcu1_0.7.12-0ubuntu2_amd64.deb:
  size: 34852
  object_id: 4d688347-d3db-4998-7e80-e5407b2c0fab
  sha: 2ac3e285032f428b9f67c3993054ed463fb4e6ab
glusterfs-client/python2.7-minimal_2.7.6-8ubuntu0.3_amd64.deb:
  size: 1186768
  object_id: 8d3b4ef2-91fe-4cf6-6ec1-73418da65ebd
  sha: fd4838f1f925eee66ef8a763a5995679c17a8dd3
glusterfs-client/python2.7_2.7.6-8ubuntu0.3_amd64.deb:
  size: 196592
  object_id: 8437a746-08d5-41be-4e31-3660df2f28ba
  sha: b86989eba577f2f998a802f653d2e8eeafdecf75
go/go1.8.linux-amd64.tar.gz:
  size: 89803580
  object_id: c150a8bd-e241-4070-46bb-8d08c2a5ee2d
  sha: a93fe8fc245e3554f956bc823f30ef4eb23c2068
jq-linux64-1.5:
  size: 3027945
  object_id: 83f251b9-8af2-41e6-4d13-5426d10109b7
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
kubernetes-1.4.6/kube-apiserver:
  size: 151001624
  object_id: 6a4b4269-5acd-4219-6d79-127bbcc94dd6
  sha: a2ec0fed640ee900723e0cc5b1b0f84253323b2f
kubernetes-1.4.6/kube-controller-manager:
  size: 141028448
  object_id: 4a305e54-8150-4f30-659e-0825849f18fa
  sha: 4e91fd7aab69c5664e0d5d47f7edea532d5b03d5
kubernetes-1.4.6/kube-proxy:
  size: 72367392
  object_id: 3139f9cc-9dde-4e7a-7d48-51d13caa7f18
  sha: 809555cb727b2ecca0e5df2244409be37df47406
kubernetes-1.4.6/kube-scheduler:
  size: 80201536
  object_id: 7f9df25d-caf7-4e21-6901-59cb343012c7
  sha: 2ae36797e45fe9fdfcbbc67fc7a73e193938e94b
kubernetes-1.4.6/kubectl:
  size: 79537832
  object_id: 4f5ab324-8b00-443e-5ed7-7b116a55f29a
  sha: 9adcd120fdb7ad6e64c061e56a05fefc12e9618b
kubernetes-1.4.6/kubelet:
  size: 129126768
  object_id: 427addf9-deed-4356-6880-4c6db1070ab3
  sha: 7d70e090951486cae52d9a82b7aaf5056f84f8ed
kubernetes-1.6.0/kube-apiserver:
  size: 149384995
  object_id: 9dde9851-5ca1-45ad-4fcb-c66d7f40f1b9
  sha: 4fb3aaabd8af239ff2184c1d714b9c2f74244786
kubernetes-1.6.0/kube-controller-manager:
  size: 131606504
  object_id: 82c94226-fbb2-4ea2-68e5-98391d7d0ea8
  sha: 8501228da7ded3c2f01b02ffd48729e59bcb2b2c
kubernetes-1.6.0/kube-proxy:
  size: 64016146
  object_id: fc042050-0dd5-4c86-4f89-97ccf0be117f
  sha: 5ca1243b4506eee02f7e3ec2396fd727323d3cae
kubernetes-1.6.0/kube-scheduler:
  size: 75637793
  object_id: 9544dc41-9392-47ea-7e44-6bb2c2c65b56
  sha: f95dec9b1871e4fea4086acf298bec53512f4973
kubernetes-1.6.0/kubectl:
  size: 70704507
  object_id: dde83133-02fc-4192-5708-09c96f8ade97
  sha: 4b63da93280ed7d43fe0abb50cf1b07170a80ca1
kubernetes-1.6.0/kubelet:
  size: 138647424
  object_id: 86440b44-05ab-4ff1-688c-0ce0310238ef
  sha: 8615f267615c5f07ec9522e13652df8417890cbf
nginx/nginx-release-1.11.4.tar.gz:
  size: 987038
  object_id: 1ea9f195-34d4-46f3-7ecd-87687e7e1d76
  sha: deecc5583de7f250c6f30e8028589d3b09a58a83
nginx/pcre-8.39.tar.gz:
  size: 2062258
  object_id: 96795e8e-c37d-415a-769a-381466466146
  sha: b3aec1f643d9701841e2f9d57ac121a7ff448fc8
