cni/cni-amd64-v0.5.2.tgz:
  size: 14085755
  object_id: 31cb39af-c33d-4df8-4d45-c02541806e39
  sha: 71f411080245aa14d0cc06f6824e8039607dd9e9
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
container-images/gcr.io_google_containers_heapster:v1.1.0.tgz:
  size: 32207205
  object_id: d2bef095-4048-4d56-5a5c-a5bd759b23fd
  sha: 70c7b90bf79d9714a974aa0b422941b568264424
container-images/gcr.io_google_containers_k8s-dns-dnsmasq-nanny-amd64:1.14.4.tgz:
  size: 11312816
  object_id: 02c5797d-f187-4267-5e18-ead0c963a9a3
  sha: 7bd901c11e10b76459bfe24e02a00a291489c7e3
container-images/gcr.io_google_containers_k8s-dns-kube-dns-amd64:1.14.4.tgz:
  size: 13106474
  object_id: b85062f0-2894-444b-58c7-c5a1c9e2ab53
  sha: bbb4fcc61c4f4611b70cf78b6af4a0ef63548c6b
container-images/gcr.io_google_containers_k8s-dns-sidecar-amd64:1.14.4.tgz:
  size: 11338507
  object_id: 3ed89f1a-e8f3-4aa7-595b-babcfd1394c5
  sha: dad574f7b4200bdabae3333c105f2e5d66e3a815
container-images/gcr.io_google_containers_kubernetes-dashboard-amd64:v1.6.1.tgz:
  size: 37658880
  object_id: 52d29c5a-4db6-40e6-73d4-18a31d9cae20
  sha: 5320eb3434d4f53979bc82d86eb968468abe6cf3
container-images/gcr.io_google_containers_pause-amd64:3.0.tgz:
  size: 313309
  object_id: 7af46f58-b711-491a-4142-048930964b81
  sha: 51d94c9d97106024454f20bf443132058e3d9334
container-images/gcr.io_google_containers_pause.tgz:
  size: 71680
  object_id: 018df5e0-9afe-4f68-4552-c08a692a991e
  sha: 7b82730258d143602b85efa7ec2da5bc754f3a93
container-images/kubernetes_heapster_influxdb:v0.6.tgz:
  size: 105081408
  object_id: ede99e38-9127-45e3-65a5-6b572c881930
  sha: cc33af2580eead375bb1ebf5d2cacf6dc71477a8
etcdctl:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flanneld:
  size: 21599816
  object_id: 2e653718-cede-4af5-73ea-d5774e7caad3
  sha: 63076521f1ba5605fa5f97016072a4538d66740f
go/go1.8.linux-amd64.tar.gz:
  size: 89803580
  object_id: be776520-f271-439d-511a-9a0f63013403
  sha: a93fe8fc245e3554f956bc823f30ef4eb23c2068
govc_linux_amd64.gz:
  size: 5941851
  object_id: e7f1ebef-4ccf-48bb-6ba6-f46ec47ed4f3
  sha: 79db9661d65b265856976b360ee4ce84de761fa9
jq-linux64-1.5:
  size: 3027945
  object_id: 41eb1cd1-0377-4e08-5602-51e0af8b9b52
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
kubernetes-1.7.6/kube-apiserver:
  size: 184984196
  object_id: a876d9bc-4893-41da-4bef-d16cf15aebdc
  sha: 32686c5472033feb0d5e3798bd7ab961205d1f32
kubernetes-1.7.6/kube-controller-manager:
  size: 136868878
  object_id: 4f03f061-da01-4321-768d-9fc403e5cf69
  sha: ae2d586a0477d77b697b487f414f2a76d2e23a73
kubernetes-1.7.6/kube-proxy:
  size: 69695477
  object_id: df4eac59-e5c7-4b63-557c-06842d09a14c
  sha: 98c406f8753268f95d32679dc7aa82ad91fab748
kubernetes-1.7.6/kube-scheduler:
  size: 76075083
  object_id: 06f13b36-ac29-43f6-647e-de04ddd6adbd
  sha: 9048dae1649571a3bc1d108d5f08f38fce780cd5
kubernetes-1.7.6/kubectl:
  size: 72341627
  object_id: 08a95028-4d59-4be8-4cb0-afecb95943c6
  sha: e5151770a5f896f50435dcca15e96c8296b778ff
kubernetes-1.7.6/kubelet:
  size: 146191832
  object_id: e73bd14e-ce99-4158-44c9-73d8f5586312
  sha: ee007f4d30a9f5002a7e4e7ea4ae446b34a174cf
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
