cni/cni-amd64-v0.5.2.tgz:
  size: 14085755
  object_id: 31cb39af-c33d-4df8-4d45-c02541806e39
  sha: 71f411080245aa14d0cc06f6824e8039607dd9e9
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
container-images/gcr.io_google_containers_k8s-dns-dnsmasq-nanny-amd64:1.14.8.tgz:
  size: 10940805
  object_id: 97a35aca-59c0-4e22-7d05-cc0de22f1e08
  sha: fdec9e001af4290f638e30ae381cda27b6e964f5
container-images/gcr.io_google_containers_k8s-dns-kube-dns-amd64:1.14.8.tgz:
  size: 13181223
  object_id: 730ad60c-29ed-4bf4-52e2-3f82bf5d281e
  sha: 4f3058395927070aac9bf6085bd638cbf4236cbb
container-images/gcr.io_google_containers_k8s-dns-sidecar-amd64:1.14.8.tgz:
  size: 11240942
  object_id: 7b67f40e-6428-4441-459b-858ef4151389
  sha: 71f699220f8685114493ac82428835294eaea869
container-images/gcr.io_google_containers_kubernetes-dashboard-amd64:v1.8.2.tgz:
  size: 37217815
  object_id: c3b9d396-8537-498d-403a-3afc628ee3c7
  sha: de1fc537fa30c9547087a64ceb36e415b38f37ae
container-images/gcr.io_google_containers_pause-amd64:3.0.tgz:
  size: 313309
  object_id: 7af46f58-b711-491a-4142-048930964b81
  sha: 51d94c9d97106024454f20bf443132058e3d9334
container-images/gcr.io_google_containers_pause.tgz:
  size: 71680
  object_id: 018df5e0-9afe-4f68-4552-c08a692a991e
  sha: 7b82730258d143602b85efa7ec2da5bc754f3a93
container-images/k8s.gcr.io_heapster-amd64:v1.5.1.tgz:
  size: 19797523
  object_id: a2021a88-1662-42f5-7a45-152d2e1501fe
  sha: 9f7e11ff96729c7d531631e2217272e63bca3d37
container-images/k8s.gcr.io_heapster-influxdb-amd64:v1.3.3.tgz:
  size: 4751608
  object_id: 72e0b4f1-269e-4174-4e47-e1598bf0e8cb
  sha: d116fc1985e78f7fa116a10a538ada383d867da8
etcdctl-3.0.7:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flannel-v0.10.0-linux-amd64.tar.gz:
  size: 9706487
  object_id: 36a8e66a-0b6c-4ca2-5f27-c277a7db90c5
  sha: 9d19a56847d6aad207671a349eddd85de87ba560
govc_v0.17.0_linux_amd64.gz:
  size: 8584489
  object_id: 091e453e-d918-4081-4356-0aeb16f793f8
  sha: 5770ee24e2a12e975e19a11dace3725dcb5ac968
jq-linux64-1.5:
  size: 3027945
  object_id: 41eb1cd1-0377-4e08-5602-51e0af8b9b52
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
kubernetes-1.9.3/kube-apiserver:
  size: 209306907
  object_id: d5143634-255e-4249-5920-241d13c25ad0
  sha: 78d2494d7143aa4548ea5faedbdefcbdd57930e4
kubernetes-1.9.3/kube-controller-manager:
  size: 136680621
  object_id: 404a06db-501a-41a0-509e-cf24e3a5dbfc
  sha: dc5d59d39ca65eb8254c87df4e461ff4c6a0a564
kubernetes-1.9.3/kube-proxy:
  size: 63378854
  object_id: a3d61b1c-09d8-4bb0-52ea-b5a549fc9355
  sha: 2b127358a4780d54a431fafbd134874a48c30e74
kubernetes-1.9.3/kube-scheduler:
  size: 61566871
  object_id: 9641bcf7-e53a-4b40-5072-d2e0d0e1adf2
  sha: 34b09e6675503d178ea92c8a691e1a22838b7e48
kubernetes-1.9.3/kubectl:
  size: 67390456
  object_id: f6fd18dc-b335-4b5d-7a0d-dcbf9745244a
  sha: a27d808eb011dbeea876fe5326349ed167a7ed28
kubernetes-1.9.3/kubelet:
  size: 147799384
  object_id: 9eebf426-6013-481b-4205-353f9c8ca703
  sha: ef979a00ba2f7bf4ee5023e82f94ced2d94c1726
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
