autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: 50feb35a-e388-4fb0-4313-3a47e82fad22
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
cifs-utils-6.7.tar.bz2:
  size: 363647
  object_id: c529967d-57fa-4b41-685e-ff0a507ffaad
  sha: 9ba5091d7c2418a90773c861f04a3f4a36854c14
cni/cni-plugins-amd64-v0.7.1.tgz:
  size: 17108856
  object_id: 50dc58eb-107d-483a-4e37-5a243ffed520
  sha: fb29e20401d3e9598a1d8e8d7992970a36de5e05
cni/cni-plugins-windows-amd64-c74e0e996.tgz:
  size: 9678154
  object_id: da0e8048-675b-4701-68e9-7db89e88723b
  sha: 02c4d67a17a28c26cc471e56bf01dcacd104b346
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
conntrack/conntrack_1.4.1-1.deb:
  size: 25112
  object_id: 9bf859c2-93aa-48b0-69f9-5903f0b4acbe
  sha: 494df11d77a1dd31fbc1e0e8c7946957ef5a74af
conntrack/libnetfilter-conntrack3_1.0.4-1.deb:
  size: 45872
  object_id: 42a59368-8ae3-4502-480b-56ecd3f40f7a
  sha: 743b497bd6a6491a8cad11c04103e55c7a9cc93c
container-images/coredns_coredns:1.4.0.tgz:
  size: 12997721
  object_id: 14779ec2-2266-48eb-77d6-a732d3721d1f
  sha: b5f7af681ba11570d7ffdf77f9f6c03371b45679
container-images/k8s.gcr.io_kubernetes-dashboard-amd64:v1.10.1.tgz:
  size: 44852477
  object_id: 1d8fdcd7-fe1e-431d-5d90-2032b97d8ad0
  sha: 8a19204a0a3f75c5a4f495b1cd3bb1c7d604fa6c
container-images/k8s.gcr.io_metrics-server-amd64:v0.3.3.tgz:
  size: 10376132
  object_id: e74f3c71-252b-47a0-7357-f54feebaf0dd
  sha: 3ef24cca1418d8e00104e2f87abefe8f4777db8b
container-images/k8s.gcr.io_pause:3.1.tgz:
  size: 315592
  object_id: f6ba8b90-9a60-454d-73e0-cab4b1c4a554
  sha: d4095b6513b3d5ef770c44d651ae5601878906d8
container-images/pcfkubo_nginx-bionic:1.0.0.tgz:
  size: 77661967
  object_id: f2575255-59f6-442e-5f69-d10e5a24e178
  sha: c677df2c93e1a15604285ea0f32b121011dcacdd
etcdctl-3.0.7:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flannel-v0.11.0-linux-amd64.tar.gz:
  size: 9565743
  object_id: 83064ebe-b45d-4d41-694a-b1e61a781250
  sha: 3024034b2202d5940acf5353037161ea1770a9c5
flannel-v0.11.0-windows-amd64.tar.gz:
  size: 9488010
  object_id: 968eac5f-3008-4bcf-5481-f3f4179162d4
  sha: 71cb61a487c40df8eeb4d2bd68d7e891b51b44bb
ipset/ipset_6.20.1-1_amd64.deb:
  size: 34156
  object_id: 5dfcce8f-366e-49f0-59e6-9e2d48178750
  sha: 79eb9008d1a57b31bc748b49c18701ab3dd41108
ipset/libipset3_6.20.1-1_amd64.deb:
  size: 50812
  object_id: 67efec49-e111-45fc-701d-7d55dbe66660
  sha: e4daa1ac22b2775d1c334aa6fe055ca8dcccc185
jq-linux64-1.6:
  size: 3953824
  object_id: efdcc8cd-7155-47d4-65c9-d3d74700633f
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
kubernetes-1.14.6/kube-apiserver:
  size: 167111968
  object_id: 8b5d619d-bccd-4d67-6302-b7a6c2e84e3a
  sha: ba3bc2bd7672ec12efa64bcbab85376a8efc1216
kubernetes-1.14.6/kube-controller-manager:
  size: 115137024
  object_id: c34aaba0-6142-418e-43bf-9f35ab11f82d
  sha: 72d0c9122a073c6535ccca584c23d5a318c54fd3
kubernetes-1.14.6/kube-proxy:
  size: 36685440
  object_id: 81764ea2-33ff-4dd7-7ba8-3bfc9ea360e7
  sha: 9816def0299863a80c028a53fe36714af3351ba1
kubernetes-1.14.6/kube-scheduler:
  size: 39258304
  object_id: 41ce4bad-f9e2-491d-731f-c98c1142c717
  sha: dbee59051dbadecdb078943bd992947e38510d08
kubernetes-1.14.6/kubectl:
  size: 43107136
  object_id: b47c9000-e703-4760-5a0f-c27eab974eda
  sha: 8a46184b3dd30bcc617da7787bc5971dc6a8233c
kubernetes-1.14.6/kubelet:
  size: 128063344
  object_id: 8912fcda-70aa-4849-5d59-246c57ac84e9
  sha: b5022066bdb4833407bcab2e636bb165a9ee7a95
kubernetes-windows-1.14.6/kube-proxy.exe:
  size: 39767040
  object_id: fe3a1657-c4c3-402c-467c-7d0d6d155e05
  sha: 06190952347402d94752969214be23896ace203d
kubernetes-windows-1.14.6/kubectl.exe:
  size: 43557376
  object_id: bfb416f8-d389-416a-77ca-af06c19e46a5
  sha: 837d12ab22750c0f8e9bba68adb1a54490afcb6d
kubernetes-windows-1.14.6/kubelet.exe:
  size: 116739072
  object_id: 24e46a2a-b1ed-48d8-716b-fd9c957b2e7d
  sha: a0a455d8646cb7325ddc7743324efc53ac90ba18
libmnl0_1.0.3-3.deb:
  size: 11416
  object_id: 245e085f-1ad2-447d-67bb-1894b960c571
  sha: dcb0b572f1207ad192d8cb1a9010fc6dd22d0000
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 670cc8a2-75d8-4fb5-465f-270395cb9373
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: e1b42c34-4e88-426b-7268-99d1bdfd40c1
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: cbdc50ad-e7f5-4a3b-6115-77392061bd76
  sha: 57d69f44f3e058e48a7b79595d36076eb21f5942
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 59ba4d66-fb63-4a62-75da-8502169d85cd
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1:1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: 6c99be77-1ba2-4be4-409a-36c090035646
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 56ad455e-38be-40da-7815-a9d4774d55e4
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 2a0b553f-c65d-42ef-6317-dd0cfcdc7c06
  sha: 76e501663b29cb7580245720edfb6106164fad2b
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
talloc-2.1.9.tar.gz:
  size: 440335
  object_id: f2d8d5e1-1cb6-450c-480f-015534a76b17
  sha: e1e79fec4c0b6bd92be904a9c03b0a168478711a
