autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: 50feb35a-e388-4fb0-4313-3a47e82fad22
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
cifs-utils-6.7.tar.bz2:
  size: 363647
  object_id: c529967d-57fa-4b41-685e-ff0a507ffaad
  sha: 9ba5091d7c2418a90773c861f04a3f4a36854c14
cni/cni-plugins-amd64-v0.7.1.tgz:
  size: 17108856
  object_id: 50dc58eb-107d-483a-4e37-5a243ffed520
  sha: fb29e20401d3e9598a1d8e8d7992970a36de5e05
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
conntrack/conntrack_1.4.3-3_amd64.deb:
  size: 27346
  object_id: 0c4aa633-3de8-4a8c-7170-36b3fc9e4a9c
  sha: sha256:ad9eae1cf2191981dd687b681ee701a2f3adfca5b89b45c2ff74c0f8d32113ff
conntrack/libnetfilter-conntrack3_1.0.5-1_amd64.deb:
  size: 36634
  object_id: 1d6d9546-e933-46bd-60f9-00bd8eb91c59
  sha: sha256:18609b2b131bc0dedf4a2c3fbf61b30d16c3d3a96cd43d604e8fc53ebc1e30eb
container-images/coredns_coredns:1.4.0.tgz:
  size: 12997721
  object_id: 14779ec2-2266-48eb-77d6-a732d3721d1f
  sha: b5f7af681ba11570d7ffdf77f9f6c03371b45679
container-images/k8s.gcr.io_metrics-server-amd64:v0.3.6.tgz:
  size: 10382760
  object_id: ce583d21-d693-492d-71f8-8f40bdf54d43
  sha: 31569430e282f25a62c9c717ad384a38495f4757
container-images/k8s.gcr.io_pause:3.1.tgz:
  size: 315592
  object_id: f6ba8b90-9a60-454d-73e0-cab4b1c4a554
  sha: d4095b6513b3d5ef770c44d651ae5601878906d8
container-images/pcfkubo_nginx-bionic:1.0.0.tgz:
  size: 77661967
  object_id: f2575255-59f6-442e-5f69-d10e5a24e178
  sha: c677df2c93e1a15604285ea0f32b121011dcacdd
etcdctl-3.0.7:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flannel-v0.12.0-linux-amd64.tar.gz:
  size: 9565406
  object_id: 71fed4a3-0db3-4f50-4064-c7e93b4e5ae9
  sha: 745cf6eb3897ab97ee1362cd401262a0e0038524
ipset/ipset_6.20.1-1_amd64.deb:
  size: 34156
  object_id: 5dfcce8f-366e-49f0-59e6-9e2d48178750
  sha: 79eb9008d1a57b31bc748b49c18701ab3dd41108
ipset/libipset3_6.20.1-1_amd64.deb:
  size: 50812
  object_id: 67efec49-e111-45fc-701d-7d55dbe66660
  sha: e4daa1ac22b2775d1c334aa6fe055ca8dcccc185
jq-linux64-1.6:
  size: 3953824
  object_id: efdcc8cd-7155-47d4-65c9-d3d74700633f
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
kubernetes-1.17.12/kube-apiserver:
  size: 118808576
  object_id: e0981a13-5d0d-483d-71d3-ed8ab1e16e07
  sha: sha256:f06b716440d41ff2e7d842492d96827d85127a6ffdd5a270c838a92d71ee301c
kubernetes-1.17.12/kube-controller-manager:
  size: 108683264
  object_id: b42a0039-53c0-4636-66d5-9712a12d74aa
  sha: sha256:6e3bee63ad5472b4561c16298628c107b8cd7bfbc9a8c592392fc0d2542951e8
kubernetes-1.17.12/kube-proxy:
  size: 37814272
  object_id: 9eeed75f-f891-40e0-53cb-216822a7565c
  sha: sha256:4efe34b1fd0beb727eb6a974878fd898498461876673cd6655e853b549666827
kubernetes-1.17.12/kube-scheduler:
  size: 42123264
  object_id: f81ec427-a4be-4be2-5cc4-73979c98eec9
  sha: sha256:c64666f9b42a3bd6f11146c8008b8331dfa49a58263aa5de11d531470f98bf91
kubernetes-1.17.12/kubectl:
  size: 43515904
  object_id: 648742a3-04d3-4984-4068-e43a2d113073
  sha: sha256:d6472a5f5d3ff125b4a1aa5cefd6197faadfb578c36f639240a04df1a71597e1
kubernetes-1.17.12/kubelet:
  size: 111708120
  object_id: f1bea7e8-4b21-42c0-4d14-87f53ab6fbed
  sha: sha256:196263deb2605507ff137b3edea39a914e7047f4c4de0a681c4a6f8dcfa5fe65
libmnl0_1.0.3-5_amd64.deb:
  size: 11970
  object_id: 30b1e2c0-4194-47f2-544f-f55eb76b9101
  sha: sha256:abd749bdd206e51fc9ac19ef27d4452a2d9df46b5b1a276d50a065af901ab1c4
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 670cc8a2-75d8-4fb5-465f-270395cb9373
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: e1b42c34-4e88-426b-7268-99d1bdfd40c1
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 0fa38188-cd2c-417f-7407-02367bc99c7d
  sha: sha256:e1acdffde386a4da7de46166ffd199771a13498f5d4fc38d61b3fa0eba305572
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 59ba4d66-fb63-4a62-75da-8502169d85cd
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1:1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: 6c99be77-1ba2-4be4-409a-36c090035646
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 56ad455e-38be-40da-7815-a9d4774d55e4
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 2a0b553f-c65d-42ef-6317-dd0cfcdc7c06
  sha: 76e501663b29cb7580245720edfb6106164fad2b
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
talloc-2.1.9.tar.gz:
  size: 440335
  object_id: f2d8d5e1-1cb6-450c-480f-015534a76b17
  sha: e1e79fec4c0b6bd92be904a9c03b0a168478711a
