cni/cni-amd64-v0.5.2.tgz:
  size: 14085755
  object_id: 31cb39af-c33d-4df8-4d45-c02541806e39
  sha: 71f411080245aa14d0cc06f6824e8039607dd9e9
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
conntrack/conntrack_1.4.1-1.deb:
  size: 25112
  sha: 494df11d77a1dd31fbc1e0e8c7946957ef5a74af
conntrack/libmnl0_1.0.3-3.deb:
  size: 11416
  sha: dcb0b572f1207ad192d8cb1a9010fc6dd22d0000
conntrack/libnetfilter-conntrack3_1.0.4-1.deb:
  size: 45872
  sha: 743b497bd6a6491a8cad11c04103e55c7a9cc93c
container-images/gcr.io_google_containers_k8s-dns-dnsmasq-nanny-amd64:1.14.8.tgz:
  size: 10940805
  object_id: 97a35aca-59c0-4e22-7d05-cc0de22f1e08
  sha: fdec9e001af4290f638e30ae381cda27b6e964f5
container-images/gcr.io_google_containers_k8s-dns-kube-dns-amd64:1.14.8.tgz:
  size: 13181223
  object_id: 730ad60c-29ed-4bf4-52e2-3f82bf5d281e
  sha: 4f3058395927070aac9bf6085bd638cbf4236cbb
container-images/gcr.io_google_containers_k8s-dns-sidecar-amd64:1.14.8.tgz:
  size: 11240942
  object_id: 7b67f40e-6428-4441-459b-858ef4151389
  sha: 71f699220f8685114493ac82428835294eaea869
container-images/gcr.io_google_containers_kubernetes-dashboard-amd64:v1.8.3.tgz:
  size: 37246406
  object_id: 0f03b2e6-2eb4-4d16-542d-ec9aa5753ad8
  sha: 63af8451dd262e2d4068a090029a8f8514aece1c
container-images/gcr.io_google_containers_pause-amd64:3.0.tgz:
  size: 313309
  object_id: 7af46f58-b711-491a-4142-048930964b81
  sha: 51d94c9d97106024454f20bf443132058e3d9334
container-images/gcr.io_google_containers_pause.tgz:
  size: 71680
  object_id: 018df5e0-9afe-4f68-4552-c08a692a991e
  sha: 7b82730258d143602b85efa7ec2da5bc754f3a93
container-images/k8s.gcr.io_heapster-amd64:v1.5.1.tgz:
  size: 19797523
  object_id: a2021a88-1662-42f5-7a45-152d2e1501fe
  sha: 9f7e11ff96729c7d531631e2217272e63bca3d37
container-images/k8s.gcr.io_heapster-influxdb-amd64:v1.3.3.tgz:
  size: 4751608
  object_id: 72e0b4f1-269e-4174-4e47-e1598bf0e8cb
  sha: d116fc1985e78f7fa116a10a538ada383d867da8
etcdctl-3.0.7:
  size: 18427584
  object_id: 32221476-5c3d-4ec7-5869-44c989cc3077
  sha: 11f0462cc86bf85332399a2fa584d5bb46d0cb2a
flannel-v0.10.0-linux-amd64.tar.gz:
  size: 9706487
  object_id: 36a8e66a-0b6c-4ca2-5f27-c277a7db90c5
  sha: 9d19a56847d6aad207671a349eddd85de87ba560
govc_v0.17.0_linux_amd64.gz:
  size: 8584489
  object_id: 091e453e-d918-4081-4356-0aeb16f793f8
  sha: 5770ee24e2a12e975e19a11dace3725dcb5ac968
jq-linux64-1.5:
  size: 3027945
  object_id: 41eb1cd1-0377-4e08-5602-51e0af8b9b52
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
kubernetes-1.9.4/kube-apiserver:
  size: 210691047
  object_id: f95f7d69-2b20-4e09-618b-0d62ed42edbb
  sha: 1383b8e17d2e9748d9f85b28f1631a50a956fde7
kubernetes-1.9.4/kube-controller-manager:
  size: 138016556
  object_id: bdd61f0b-b58e-4e1d-6bc9-ce59c5c410ec
  sha: 5688789c3220125518035423b60e1c42f22232fb
kubernetes-1.9.4/kube-proxy:
  size: 63574253
  object_id: 63c0831f-2fad-45a0-49be-3b1408387528
  sha: 3af20c3bbe0ce653a31b3a7b75f795ebec0bca37
kubernetes-1.9.4/kube-scheduler:
  size: 61711295
  object_id: 0fadce1f-6978-483e-4517-678c14b238f4
  sha: 84a020ba02bf8e74e2c8634e74a25ad717f2598f
kubernetes-1.9.4/kubectl:
  size: 67557049
  object_id: f7c5f51d-5bae-4df7-4480-bb8bb7c96635
  sha: 3085aebbaa7d54b2d52730b64ae44966d8fe2954
kubernetes-1.9.4/kubelet:
  size: 147302136
  object_id: 6201aef3-79c3-4787-6a5c-d0f5628b5de1
  sha: 23337ba77a1cd3a55b22be5236045c5cdfc41292
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
